### ISSUE TITLE
Center the landing page content

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Landing-Page-Animation#1]
All you need to do is centre all the displayed content to the browser's height and width. That means, the heading/text and the image should all be centred.

**Comment by cziem** [comment]
Am taking this... am good for a go?

**Comment by rsm23** [comment]
@Kvaibhav01 please check #3

**Comment by Kvaibhav01** [comment]
@phavor it's done already. You can work on another issue (s).

**Comment by alvaromontoro** [comment]
@Kvaibhav01 the change made centers vertically, but it breaks the horizontal centering. You need to remove the `display: flex` and then it will center both vertically and horizontally.

**Comment by Kvaibhav01** [comment]
@alvaromontoro I don't think that it's not centred horizontally. Maybe I'm wrong here. Kindly make the respective PR. 😀

**Comment by alvaromontoro** [comment]
@Kvaibhav01 In large screens, it stops being centered after some pixel size. The issue that caused this ticket was caused by the height of the body not having units (it was, and still is, only 100 without any unit of measure). I will create a PR and fix it.

**Comment by rsm23** [comment]
@Kvaibhav01 what @alvaromontoro is right please check #9 it fixes the issue

**Comment by Kvaibhav01** [comment]
Got it @alvaromontoro @rsm23 😬

**Comment by alvaromontoro** [comment]
I cleaned the code and created a pull request (#11). It has less code and it centers the content both vertically and horizontally

**Comment by Kvaibhav01** [comment]
Thank you @alvaromontoro 😁 I've merged #11
