### ISSUE TITLE
Make the landing page responsive

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Landing-Page-Animation#14]
Maybe add [Bootstrap](http://getbootstrap.com/)? Kindly test the same on your tablet/mobile device(s).

**Comment by Endi1** [comment]
Could also use something very lightweight like http://flexboxgrid.com/

No need for Bootstrap if you are only going to use the grid IMO

**Comment by Kvaibhav01** [comment]
Nice idea @Endi1 ! Go ahead.

**Comment by HerrBertling** [comment]
If I may chime in: You are using CSS Grid already, why not take advantage of that instead of introducing a framework?

**Comment by kevduong** [comment]
i agree with @HerrBertling i submitted a pull request and adjusted the media query
