### ISSUE TITLE
Add glowing animation while on hover

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Landing-Page-Animation#17]
When the pointer is hovered over the following elements, they should have a glowing effect around them:

1. The login/signup button
2. The three icons over the monitor illustration.

**Comment by jChris85** [comment]
Should it only have glow or also puls? However, I can implement that for you and if you wanna change it to a puls we can do that as well.

**Comment by Kvaibhav01** [comment]
Hey @jChris85 , what is a puls effect? Is it really puls or is it _pull_ effect? Any resources so that I can check it out?

**Comment by jChris85** [comment]
@Kvaibhav01 something like that, but on hover of course. This is possible for the button for sure. I have to check out if this is possible for the SVG icons as well.

https://codepen.io/wifeo/pen/KwdXwV

**Comment by Kvaibhav01** [comment]
That looks cool. Implement that in the button 😀

**Comment by jChris85** [comment]
@Kvaibhav01 I´ve added the pulse effect to the CTA when the button will be hovered. Unfortunatly I can not style the icons because they are SVGs loaded as an image tag. To get full control for the SVG styling it would be better to make implement them as an inline SVG. Then the pulse effect would also be possible for the icons.

P.s.: I really like the design of that page

**Comment by marekgebka** [comment]
@jChris85 I think I can update the SVG-stuff. When it's merged you should be able to add your CSS.

**Comment by jChris85** [comment]
@marekgebka that would be nice, thx.

**Comment by Kvaibhav01** [comment]
@jChris85 don't know why but the pulse effect is not working. 😞 I merged your PR, nothing happens when I hover over the button.

**Comment by jChris85** [comment]
@Kvaibhav01 I will take a look.

**Comment by jChris85** [comment]
@Kvaibhav01 Sorry I can see the effect in all common browsers. Even IE11 is showing it. On wich device and browser are you testing?

The effect is very minimalistic...maby you just have to increase the opacity.

**Comment by Kvaibhav01** [comment]
@jChris85, now it's showing. Don't know why it wasn't before. Thanks!
