### ISSUE TITLE
Update miota's bubble text

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Landing-Page-Animation#2]
Currently, the miota's bubble text (which says "great work!") is not like other bubble text. Fix that.

**Comment by rsm23** [comment]
@Kvaibhav01 please check my last commit #4

**Comment by Kvaibhav01** [comment]
I've merged but can you add that border around the message text on miota? You can do this with any vector application like XD or Illustrator. When you're done make another PR. 😀

**Comment by rsm23** [comment]
I've added the border around the text, haven't I?

**Comment by rsm23** [comment]
Ok, check number #6

**Comment by Kvaibhav01** [comment]
Check this [review](https://github.com/Kvaibhav01/Landing-Page-Animation/pull/6#pullrequestreview-160864301).
