### ISSUE TITLE
Add demo GIF to the README

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Landing-Page-Animation#5]
Just capture the animation of the landing page and add the GIF in the README file.

**Comment by jkaan** [comment]
@Kvaibhav01 I can do this one!

**Comment by agoel00** [comment]
Can I take this issue?

**Comment by Kvaibhav01** [comment]
Yes @jkaan and @agoel00 go ahead!

**Comment by Kvaibhav01** [comment]
@jkaan @agoel00 kindly wait. We need to fix the font of miota first then we can work on GIF. See #2

**Comment by vaibhavvijay9** [comment]
Done.
![landing_screen](https://user-images.githubusercontent.com/29380667/46492078-33521880-c82a-11e8-8cbc-06f91ccb263b.gif)
